---
#  We install pymongo from in-house epel repo, mongo from bundle
#- name: Create the MongoDB repo file
#  copy: src=mongodb.repo dest=/etc/yum.repos.d/mongodb-org-3.0.repo
#  tags:
#    - mongodb

- name: 'make sure mongo_rpm_dir is defined.'
  fail: msg='variable mongo_rpm_dir is undefined'
  when: mongo_rpm_dir is undefined

- name: Install policycoreutils-python
  yum: name=policycoreutils-python state=installed
  tags:
    - mongodb

- name: Install pymongo
  yum: name=python-pymongo state=present
  tags:
    - mongodb

- name: Install MongoDB
  yum: "name={{ item }} state=present"
  notify: restart mongod
  with_items: '{{ mongo_rpms }}'
  tags:
    - mongodb

- name: Copy the configuration file
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  notify: restart mongod
  tags:
    - mongodb

- name: Copy limits file
  copy: src=mongo_limits.conf dest=/etc/security/limits.d/mongo_limits.conf
        owner=root group=root
  notify: restart mongod
  tags:
    - mongodb

#- name: Check if MongoDB port is already configured
#  shell: semanage port -l | grep {{ mongo_net.port }}
#  register: mongo_port
#  changed_when: "'mongod_port_t' not in mongo_port.stdout or ' {{ mongo_net.port }},' not in mongo_port.stdout"

#- name: Open port for MongoDB
#  command: semanage port -a -t mongod_port_t -p tcp {{ mongo_net.port }}
#  notify: restart mongod
#  when: mongo_port.changed

- name: 'Install mongod start script'
  copy: src=mongod.j2
        dest=/etc/init.d/mongod
        mode=0755
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"
  notify: restart mongod
  tags:
    - mongodb

- name: Enable mongod service on startup
  service: name=mongod enabled=yes
  tags:
    - mongodb

- name: Start mongod
  service: name=mongod state=started
  tags:
    - mongodb

- name: Create Mongo user
  mongodb_user: name={{ mongo_username }}
                password={{ mongo_password }}
                database={{ mongo_database }}
  tags:
    - mongodb
