---

- name: 'Install Python rpm dependencies'
  yum: name={{item}} state=present
  with_items:
    - python-pyasn1
    - python-requests
    - python-click
  tags:
    - towercli

- name: 'copy requirements.txt'
  copy: src=requirements.txt dest=/tmp/requirements.txt
  tags:
    - towercli

- name: 'pip install dependencies'
  pip: requirements=/tmp/requirements.txt state=present
  tags:
    - towercli

- name: 'Configure tower host'
  command: tower-cli --help
  changed_when: no
  tags:
    - towercli
    - test

- name: 'Configure tower host'
  command: tower-cli config host {{tower_host}}
  changed_when: yes
  tags:
    - towercli

- name: 'Configure tower username'
  command: tower-cli config username {{tower_user}}
  changed_when: yes
  tags:
    - towercli

- name: 'Configure tower password'
  command: tower-cli config password {{tower_password}}
  changed_when: yes
  tags:
    - towercli

- name: 'Configure Tower for imperfect SSL certificates'
  command: tower-cli config verify_ssl false
  changed_when: no
  tags:
    - towercli
