---

- name: 'Install Python rpm dependencies'
  command: yum -y install {{item}}
  with_items:
    - python-pyasn1
    - python-requests
    - python-click
  tags:
    - towercli

- name: 'copy requirements.txt'
  copy: src=requirements.txt dest=/tmp/requirements.txt
  tags:
    - towercli
    
- name: 'pip install dependencies'
  pip: requirements=/tmp/requirements.txt state=latest
  tags:
    - towercli
    
- name: 'Configure tower host'
  command: tower-cli --help
  tags:
    - towercli
    - test

- name: 'Configure tower host'
  command: tower-cli config host {{tower_host}}
  tags:
    - towercli

- name: 'Configure tower username'
  command: tower-cli config username {{tower_user}}
  tags:
    - towercli

- name: 'Configure tower password'
  command: tower-cli config password {{tower_password}}
  tags:
    - towercli

- name: 'Configure Tower for imperfect SSL certificates'
  command: tower-cli config verify_ssl false
  tags:
    - towercli

