---
# Version to be installed, must be >= 2.6
mongo_version: 3.2.6

rh: el{{ ansible_distribution_major_version }}

mongo_rpms:
  - "{{ mongo_rpm_dir }}/mongodb-org-{{ mongo_version }}-1.{{rh}}.x86_64.rpm"
  - "{{ mongo_rpm_dir }}/mongodb-org-server-{{ mongo_version }}-1.{{rh}}.x86_64.rpm"
  - "{{ mongo_rpm_dir }}/mongodb-org-shell-{{ mongo_version }}-1.{{rh}}.x86_64.rpm"
  - "{{ mongo_rpm_dir }}/mongodb-org-mongos-{{ mongo_version }}-1.{{rh}}.x86_64.rpm"
  - "{{ mongo_rpm_dir }}/mongodb-org-tools-{{ mongo_version }}-1.{{rh}}.x86_64.rpm"

# Network
mongo_net:
    ip: 0.0.0.0
    port: 27017

# Logs
mongo_logs:
    path: /var/log/mongodb/mongod.log
    append: true

# Database
mongo_db:
    path: /var/lib/mongo
