---

postgres_repo: "http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-redhat94-9.4-1.noarch.rpm"

postgres_packages:
  - postgresql94-server
  - postgresql94-contrib
  - perl-DBD-Pg
  - python-psycopg2

postgres_jdbc_url: "https://jdbc.postgresql.org/download/postgresql-9.4-1201.jdbc41.jar"
